services:
  mysql-db:
    image: mysql:8.0
    container_name: lab-mysql
    environment:
      MYSQL_DATABASE: lab_db
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "33065:3306"

  redis:
    image: redis:latest
    container_name: redis-cache
    ports:
      - "6379:6379"

